'use strict';

/* ============================================================
   FIXED QUESTION BANKS — extracted from the provided PDFs
   ============================================================
   Each bank: [ { id, question, options:[...], answer } ]

   - tally1: "Tally ERP 9 MCQ.pdf"          → 92 questions (PDF #1-100, 8 truncated)
   - tally2: "Tally ERP 9 MCQs.pdf"         → 92 questions (PDF #101-200, 8 truncated)
   - tally3: "Tally ERP 9 MCQ2.pdf"         → 92 questions (PDF #1-100, 8 truncated)

   Questions where the source PDF text was truncated (missing options
   and/or answer) are deliberately omitted — see README verification.
   ============================================================ */

var FIXED_BANKS = {

  /* ==========================================================
     SET 1 — Tally ERP 9 MCQ.pdf  (Basics, Vouchers, Inventory,
     GST, Reports, Security)  92 questions
     ========================================================== */
  tally1: [
    { id:1,  question:"What is Tally ERP 9?",
      options:["Operating System","Accounting Software","Antivirus","Web Browser"],
      answer:"Accounting Software" },
    { id:2,  question:"What is Tally mainly used for?",
      options:["Drawing","Accounting","Video Editing","Gaming"],
      answer:"Accounting" },
    { id:3,  question:"Which shortcut key is used to open Company Information in Tally ERP 9?",
      options:["Alt + F1","Alt + F3","Ctrl + F3","F12"],
      answer:"Alt + F3" },
    { id:4,  question:"Which key is used to select a company?",
      options:["F1","Alt + F1","Alt + F2","Ctrl + F1"],
      answer:"Alt + F1" },
    { id:5,  question:"Which shortcut key is used to shut a company?",
      options:["Alt + F1","Alt + F2","Alt + F3","Ctrl + F3"],
      answer:"Alt + F1" },
    { id:6,  question:"Which key opens Accounting Features?",
      options:["F11","F12","F10","F9"],
      answer:"F11" },
    { id:7,  question:"Which key opens Configuration?",
      options:["F11","F12","F2","F4"],
      answer:"F12" },
    { id:8,  question:"Which shortcut key opens the calculator in Tally?",
      options:["Ctrl + N","Ctrl + M","Ctrl + A","Alt + C"],
      answer:"Ctrl + M" },
    { id:9,  question:"Which key is used to change the date in Tally?",
      options:["F1","F2","F3","F4"],
      answer:"F2" },
    { id:10, question:"What is a voucher in Tally?",
      options:["A record of a transaction","A company","A report","A group"],
      answer:"A record of a transaction" },
    { id:11, question:"What is a Ledger?",
      options:["Account record","Company","Voucher type","Report"],
      answer:"Account record" },
    { id:12, question:"A Ledger is created under a:",
      options:["Group","Voucher","Company","Report"],
      answer:"Group" },
    { id:13, question:"What is the purpose of a Group in Tally?",
      options:["To classify Ledgers","To delete vouchers","To print reports","To close a company"],
      answer:"To classify Ledgers" },
    { id:14, question:"How many predefined Primary Groups are available in Tally ERP 9?",
      options:["15","20","28","30"],
      answer:"28" },
    { id:15, question:"Bank Account belongs to which group?",
      options:["Bank Accounts","Capital Account","Sales Accounts","Duties & Taxes"],
      answer:"Bank Accounts" },
    { id:16, question:"Capital Account represents:",
      options:["Owner's investment","Sales","Purchase","Expenses"],
      answer:"Owner's investment" },
    { id:17, question:"Sales Account is generally classified as:",
      options:["Income","Expense","Liability","Asset"],
      answer:"Income" },
    { id:18, question:"Purchase Account is generally classified as:",
      options:["Purchase/Expense","Liability","Asset","Capital"],
      answer:"Purchase/Expense" },
    { id:19, question:"Which account represents money owed by customers?",
      options:["Debtor","Creditor","Capital","Expense"],
      answer:"Debtor" },
    { id:20, question:"Which account represents money owed to suppliers?",
      options:["Debtor","Creditor","Cash","Sales"],
      answer:"Creditor" },
    { id:21, question:"Which shortcut key is commonly used to create a Ledger during voucher entry?",
      options:["Alt + C","Ctrl + C","Alt + L","Ctrl + L"],
      answer:"Alt + C" },
    { id:22, question:"Which report shows Assets and Liabilities?",
      options:["Balance Sheet","Day Book","Stock Summary","Trial Balance"],
      answer:"Balance Sheet" },
    { id:23, question:"Which report shows Income and Expenses?",
      options:["Profit & Loss Account","Balance Sheet","Stock Summary","Day Book"],
      answer:"Profit & Loss Account" },
    { id:24, question:"What is the shortcut key for Payment Voucher?",
      options:["F4","F5","F6","F7"],
      answer:"F5" },
    { id:25, question:"What is the shortcut key for Receipt Voucher?",
      options:["F5","F6","F7","F8"],
      answer:"F6" },
    { id:26, question:"What is the shortcut key for Journal Voucher?",
      options:["F4","F5","F7","F8"],
      answer:"F7" },
    { id:27, question:"What is the shortcut key for Sales Voucher?",
      options:["F8","F9","F7","F6"],
      answer:"F8" },
    { id:28, question:"What is the shortcut key for Purchase Voucher?",
      options:["F8","F9","F6","F7"],
      answer:"F9" },
    { id:29, question:"What is the shortcut key for Contra Voucher?",
      options:["F4","F5","F6","F7"],
      answer:"F4" },
    { id:30, question:"Cash deposited into Bank is recorded through:",
      options:["Payment Voucher","Receipt Voucher","Contra Voucher","Journal Voucher"],
      answer:"Contra Voucher" },
    { id:31, question:"Cash withdrawn from Bank is recorded through:",
      options:["Contra Voucher","Sales Voucher","Purchase Voucher","Receipt Voucher"],
      answer:"Contra Voucher" },
    { id:32, question:"Salary paid in cash is recorded through:",
      options:["Receipt","Payment","Contra","Sales"],
      answer:"Payment" },
    { id:33, question:"Cash received from a customer is recorded through:",
      options:["Payment","Receipt","Contra","Purchase"],
      answer:"Receipt" },
    { id:34, question:"Goods purchased for cash are recorded through:",
      options:["Purchase Voucher","Sales Voucher","Receipt Voucher","Contra Voucher"],
      answer:"Purchase Voucher" },
    { id:35, question:"Goods sold for cash are recorded through:",
      options:["Purchase Voucher","Sales Voucher","Payment Voucher","Journal Voucher"],
      answer:"Sales Voucher" },
    { id:36, question:"Credit Purchase creates a liability towards the:",
      options:["Customer","Supplier","Bank","Employee"],
      answer:"Supplier" },
    { id:37, question:"Credit Sales create an amount receivable from the:",
      options:["Supplier","Customer","Bank","Employee"],
      answer:"Customer" },
    { id:38, question:"Debit Note is mainly used for:",
      options:["Purchase Return","Sales Return","Cash Receipt","Salary Payment"],
      answer:"Purchase Return" },
    { id:39, question:"Credit Note is mainly used for:",
      options:["Sales Return","Purchase Return","Payment","Contra"],
      answer:"Sales Return" },
    { id:40, question:"Journal Voucher is mainly used for:",
      options:["Adjustment Entries","Cash Sales only","Cash Purchase only","Bank Deposit only"],
      answer:"Adjustment Entries" },
    { id:41, question:"Outstanding Expense means:",
      options:["Expense incurred but not yet paid","Expense paid in advance","Income received","Cash deposited"],
      answer:"Expense incurred but not yet paid" },
    { id:42, question:"Prepaid Expense means:",
      options:["Expense paid in advance","Expense not paid","Income received","Liability"],
      answer:"Expense paid in advance" },
    { id:43, question:"Depreciation is generally charged on:",
      options:["Fixed Assets","Sales","Capital only","Creditors"],
      answer:"Fixed Assets" },
    { id:44, question:"Trial Balance is prepared mainly to check:",
      options:["Debit and Credit balances","Only Sales","Only Cash","Only Stock"],
      answer:"Debit and Credit balances" },
    { id:45, question:"The basic accounting equation is:",
      options:["Assets = Liabilities + Capital","Assets = Sales + Purchase","Capital = Sales + Expenses","Assets = Expenses - Income"],
      answer:"Assets = Liabilities + Capital" },
    { id:46, question:"An increase in a liability is generally recorded on the:",
      options:["Debit side","Credit side","Both sides","None"],
      answer:"Credit side" },
    { id:47, question:"What does Inventory mean?",
      options:["Stock/Goods","Salary","Capital","Bank Balance"],
      answer:"Stock/Goods" },
    { id:48, question:"What is a Stock Item?",
      options:["An item maintained in inventory","A Ledger","A Voucher","A Company"],
      answer:"An item maintained in inventory" },
    { id:49, question:"Stock Group is used to:",
      options:["Classify Stock Items","Create Ledgers","Delete Vouchers","Create Companies"],
      answer:"Classify Stock Items" },
    { id:50, question:"Unit of Measure is used to:",
      options:["Measure quantity","Calculate salary","Create a Ledger","Create a company"],
      answer:"Measure quantity" },
    { id:51, question:"\"Nos.\" is an example of:",
      options:["Unit of Measure","Ledger","Group","Voucher"],
      answer:"Unit of Measure" },
    { id:52, question:"Godown means:",
      options:["Place where stock is stored","Bank","Customer","Ledger"],
      answer:"Place where stock is stored" },
    { id:53, question:"Stock Summary shows:",
      options:["Stock position","Only Profit","Only Cash","Only Tax"],
      answer:"Stock position" },
    { id:54, question:"Purchase Order is related to:",
      options:["Ordering goods from a supplier","Payment","Receipt","Salary"],
      answer:"Ordering goods from a supplier" },
    { id:55, question:"Sales Order is related to:",
      options:["Customer's order for goods","Purchase","Payment","Bank"],
      answer:"Customer's order for goods" },
    { id:56, question:"Reorder Level is related to:",
      options:["Stock Management","Salary","Capital","Tax Return"],
      answer:"Stock Management" },
    { id:57, question:"What is the full form of GST?",
      options:["Goods and Services Tax","General Sales Tax","Goods Service Trade","Government Sales Tax"],
      answer:"Goods and Services Tax" },
    { id:58, question:"GST was implemented in India on:",
      options:["1 July 2017","1 April 2016","15 August 2017","26 January 2018"],
      answer:"1 July 2017" },
    { id:59, question:"What is the full form of CGST?",
      options:["Central Goods and Services Tax","Central General Sales Tax","Common Goods Service Tax","Central Government Sales Tax"],
      answer:"Central Goods and Services Tax" },
    { id:60, question:"What is the full form of SGST?",
      options:["State Goods and Services Tax","State General Sales Tax","Service Goods Sales Tax","State Government Service Tax"],
      answer:"State Goods and Services Tax" },
    { id:61, question:"For an intra-state supply, generally which taxes apply?",
      options:["CGST + SGST","IGST only","CGST only","SGST only"],
      answer:"CGST + SGST" },
    { id:62, question:"For an inter-state supply, generally which tax applies?",
      options:["IGST","SGST","CGST only","No tax"],
      answer:"IGST" },
    { id:63, question:"How many characters are there in a GSTIN?",
      options:["10","12","15","16"],
      answer:"15" },
    { id:64, question:"Input Tax Credit is related to:",
      options:["Eligible GST paid on purchases","Salary","Capital only","Cash Balance"],
      answer:"Eligible GST paid on purchases" },
    { id:65, question:"Output GST is related to:",
      options:["GST collected on sales/supplies","Purchases only","Salary","Bank Interest"],
      answer:"GST collected on sales/supplies" },
    { id:66, question:"HSN Code is mainly related to:",
      options:["Classification of goods","Employees","Banks","Passwords"],
      answer:"Classification of goods" },
    { id:67, question:"SAC Code is mainly related to:",
      options:["Services","Goods only","Banks","Employees"],
      answer:"Services" },
    { id:68, question:"GST Tax Ledgers are generally created under:",
      options:["Duties & Taxes","Current Assets","Capital Account","Sales Accounts"],
      answer:"Duties & Taxes" },
    { id:69, question:"Taxable Value means:",
      options:["Value on which tax is calculated","Only tax amount","Only discount","Only quantity"],
      answer:"Value on which tax is calculated" },
    { id:70, question:"Day Book shows:",
      options:["Transactions/Vouchers entered during a period","Only Assets","Only Liabilities","Only Stock"],
      answer:"Transactions/Vouchers entered during a period" },
    { id:71, question:"A Ledger Report shows:",
      options:["Transactions of a particular Ledger","Only Stock","Only Company Name","Only GST Rate"],
      answer:"Transactions of a particular Ledger" },
    { id:72, question:"Outstanding Receivables means:",
      options:["Amount to be received from customers","Amount payable to suppliers","Cash in hand","Bank Balance"],
      answer:"Amount to be received from customers" },
    { id:73, question:"Outstanding Payables means:",
      options:["Amount payable to suppliers","Amount receivable from customers","Cash Balance","Capital"],
      answer:"Amount payable to suppliers" },
    { id:74, question:"Cash Flow Statement shows:",
      options:["Cash inflows and outflows","Only Profit","Only Stock","Only GST"],
      answer:"Cash inflows and outflows" },
    { id:75, question:"Restore means:",
      options:["Recovering data from a backup","Deleting data","Closing a company","Creating a Ledger"],
      answer:"Recovering data from a backup" },
    { id:76, question:"Security Control is used for:",
      options:["Data and User Security","Stock Purchase","Sales Entry","Printing only"],
      answer:"Data and User Security" },
    { id:77, question:"User Access Control is used to:",
      options:["Define user permissions","Increase stock","Reduce tax","Increase profit"],
      answer:"Define user permissions" },
    { id:78, question:"Password in Tally is used for:",
      options:["Security","Sales","Purchase","Stock"],
      answer:"Security" },
    { id:79, question:"Which shortcut key is commonly used for printing?",
      options:["Alt + P","Alt + C","Alt + S","Ctrl + P"],
      answer:"Alt + P" },
    { id:80, question:"What does Export mean in Tally?",
      options:["Taking data out in another format/location","Deleting data","Closing a company","Cancelling a voucher"],
      answer:"Taking data out in another format/location" },
    { id:81, question:"What does Import mean in Tally?",
      options:["Bringing external data into Tally","Deleting data","Printing a report","Closing a company"],
      answer:"Bringing external data into Tally" },
    { id:82, question:"Assets and Liabilities are shown in the:",
      options:["Balance Sheet","Day Book","Stock Summary","Journal"],
      answer:"Balance Sheet" },
    { id:83, question:"Liabilities mean:",
      options:["Amounts owed by the business","Assets owned by the business","Income only","Expenses only"],
      answer:"Amounts owed by the business" },
    { id:84, question:"Assets mean:",
      options:["Resources owned by the business","Amounts owed by the business","Expenses only","Sales only"],
      answer:"Resources owned by the business" },
    { id:85, question:"A Debtor is a person:",
      options:["From whom money is receivable","To whom money is payable","Who works as an employee","Who manages the bank"],
      answer:"From whom money is receivable" },
    { id:86, question:"A Creditor is a person:",
      options:["To whom money is payable","From whom money is receivable","Who is an employee","Who owns the bank"],
      answer:"To whom money is payable" },
    { id:87, question:"Capital represents:",
      options:["Owner's investment in the business","Sales","Purchase","Expenses"],
      answer:"Owner's investment in the business" },
    { id:88, question:"Gross Profit is generally calculated as:",
      options:["Sales - Cost of Goods Sold","Sales + Expenses","Assets - Liabilities","Capital - Sales"],
      answer:"Sales - Cost of Goods Sold" },
    { id:89, question:"Net Profit is affected by:",
      options:["Indirect Income and Indirect Expenses","Capital only","Cash only","Stock quantity only"],
      answer:"Indirect Income and Indirect Expenses" },
    { id:90, question:"What does Alter mean in Tally?",
      options:["Edit existing data","Print data","Delete data","Close company"],
      answer:"Edit existing data" },
    { id:91, question:"What does Delete mean in Tally?",
      options:["Remove selected data/voucher","Create a company","View a report","Calculate GST"],
      answer:"Remove selected data/voucher" },
    { id:92, question:"Which combination is most important for learning Tally ERP 9?",
      options:["Accounting + Vouchers + Inventory + GST","Typing only","Drawing only","Internet only"],
      answer:"Accounting + Vouchers + Inventory + GST" }
  ],

  /* ==========================================================
     SET 2 — Tally ERP 9 MCQs.pdf
     (Company, Ledger, Groups, Inventory, GST, Reports, Payroll)
     92 questions
     ========================================================== */
  tally2: [
    { id:101, question:"Which option is used to create a new company in Tally?",
      options:["Company Info","Display","Accounts Info","Inventory Info"],
      answer:"Company Info" },
    { id:102, question:"Which information is required while creating a company?",
      options:["Company Name","Address","Financial Year Beginning","All of the above"],
      answer:"All of the above" },
    { id:103, question:"What is the meaning of \"Maintain Accounts Only\"?",
      options:["Inventory is not maintained","Accounts are maintained","Both A and B","None"],
      answer:"Both A and B" },
    { id:104, question:"Which option is used when both accounting and inventory are required?",
      options:["Accounts Only","Accounts with Inventory","Inventory Only","Payroll Only"],
      answer:"Accounts with Inventory" },
    { id:105, question:"What is the purpose of the Financial Year Beginning field?",
      options:["To define the start of the financial year","To define company name","To define GST rate","To define password"],
      answer:"To define the start of the financial year" },
    { id:106, question:"Which key is used to access Company Features?",
      options:["F10","F11","F12","F2"],
      answer:"F11" },
    { id:107, question:"Which key is used to change company date?",
      options:["F1","F2","F3","F4"],
      answer:"F2" },
    { id:109, question:"What does \"Shut Company\" mean?",
      options:["Delete company","Close the currently loaded company","Erase all data","Backup company"],
      answer:"Close the currently loaded company" },
    { id:110, question:"Which option is used to modify company details?",
      options:["Alter","Display","Quit","Backup"],
      answer:"Alter" },
    { id:111, question:"Which feature is used to maintain employee salary records?",
      options:["Payroll","Inventory","Cost Centre","Banking"],
      answer:"Payroll" },
    { id:112, question:"Payroll is mainly related to:",
      options:["Employees and salaries","Customers","Stock","Suppliers"],
      answer:"Employees and salaries" },
    { id:113, question:"Which feature is used to allocate expenses to different departments?",
      options:["Cost Centre","Godown","Stock Group","Voucher Class"],
      answer:"Cost Centre" },
    { id:114, question:"Cost Category is used to:",
      options:["Group Cost Centres","Group Stock Items","Group Ledgers","Group Companies"],
      answer:"Group Cost Centres" },
    { id:115, question:"Which option controls the appearance and behavior of reports?",
      options:["Configuration","Company Creation","Ledger Creation","Stock Creation"],
      answer:"Configuration" },
    { id:117, question:"Which menu contains Stock Group and Stock Item options?",
      options:["Accounts Info","Inventory Info","Company Info","Gateway Info"],
      answer:"Inventory Info" },
    { id:118, question:"What is a Voucher Type?",
      options:["A type/classification of transaction","A company","A ledger group","A stock item"],
      answer:"A type/classification of transaction" },
    { id:119, question:"Can users create their own Voucher Types in Tally ERP 9?",
      options:["Yes","No","Only for Sales","Only for Purchase"],
      answer:"Yes" },
    { id:120, question:"What is the purpose of a Voucher Class?",
      options:["To automate/standardize voucher entries","To create companies","To delete ledgers","To create stock groups"],
      answer:"To automate/standardize voucher entries" },
    { id:121, question:"Which option is used to configure invoice printing?",
      options:["Printing Configuration","Company Creation","Ledger Creation","Stock Group"],
      answer:"Printing Configuration" },
    { id:122, question:"What is the purpose of \"Use Security Control\"?",
      options:["Protect company data","Create stock","Calculate profit","Record sales"],
      answer:"Protect company data" },
    { id:123, question:"Which user can normally access all features when given full rights?",
      options:["Administrator","Guest","Viewer","Operator"],
      answer:"Administrator" },
    { id:124, question:"Tally company data is stored in:",
      options:["Data files","Image files only","Music files","Video files"],
      answer:"Data files" },
    { id:125, question:"What is the main purpose of company backup?",
      options:["Data recovery","Data entry","Sales calculation","Stock creation"],
      answer:"Data recovery" },
    { id:126, question:"Which group is used for customers who owe money to the business?",
      options:["Sundry Debtors","Sundry Creditors","Cash-in-Hand","Capital Account"],
      answer:"Sundry Debtors" },
    { id:127, question:"Which group is used for suppliers to whom money is payable?",
      options:["Sundry Debtors","Sundry Creditors","Current Assets","Direct Income"],
      answer:"Sundry Creditors" },
    { id:128, question:"Rent paid is generally classified as:",
      options:["Indirect Expense","Direct Income","Current Asset","Liability"],
      answer:"Indirect Expense" },
    { id:129, question:"Wages directly related to production are generally:",
      options:["Direct Expense","Indirect Expense","Indirect Income","Liability"],
      answer:"Direct Expense" },
    { id:130, question:"Commission received is generally:",
      options:["Indirect Income","Direct Expense","Liability","Asset"],
      answer:"Indirect Income" },
    { id:131, question:"Carriage Inward is generally classified as:",
      options:["Direct Expense","Indirect Income","Current Liability","Capital"],
      answer:"Direct Expense" },
    { id:133, question:"Interest Received is generally:",
      options:["Indirect Income","Direct Expense","Liability","Purchase"],
      answer:"Indirect Income" },
    { id:134, question:"Discount Allowed is generally:",
      options:["Indirect Expense","Indirect Income","Asset","Liability"],
      answer:"Indirect Expense" },
    { id:135, question:"Discount Received is generally:",
      options:["Indirect Income","Direct Expense","Asset","Capital"],
      answer:"Indirect Income" },
    { id:136, question:"A Fixed Asset is purchased primarily for:",
      options:["Long-term business use","Immediate resale only","Paying salary","Collecting tax"],
      answer:"Long-term business use" },
    { id:137, question:"Furniture is an example of:",
      options:["Fixed Asset","Current Liability","Income","Expense only"],
      answer:"Fixed Asset" },
    { id:138, question:"Machinery is generally classified as:",
      options:["Fixed Asset","Current Liability","Income","Debtor"],
      answer:"Fixed Asset" },
    { id:139, question:"Loan taken by a business is generally a:",
      options:["Liability","Revenue","Expense","Current Asset"],
      answer:"Liability" },
    { id:140, question:"Interest on Loan is generally:",
      options:["Expense","Asset","Capital","Sales"],
      answer:"Expense" },
    { id:141, question:"Drawings by the owner reduce:",
      options:["Capital","Sales","Purchase","Creditors"],
      answer:"Capital" },
    { id:142, question:"Goods returned to a supplier are called:",
      options:["Purchase Return","Sales Return","Sales","Purchase"],
      answer:"Purchase Return" },
    { id:143, question:"Goods returned by a customer are called:",
      options:["Sales Return","Purchase Return","Purchase","Expense"],
      answer:"Sales Return" },
    { id:144, question:"A Trial Balance contains:",
      options:["Ledger balances","Only stock items","Only invoices","Only employees"],
      answer:"Ledger balances" },
    { id:145, question:"If total Debit equals total Credit in Trial Balance, it indicates:",
      options:["Arithmetic agreement","Guaranteed absence of all errors","Profit","Loss"],
      answer:"Arithmetic agreement" },
    { id:146, question:"Which account is credited when cash sales are made?",
      options:["Sales Account","Cash Account","Purchase Account","Expense Account"],
      answer:"Sales Account" },
    { id:147, question:"Which account is debited when cash sales are made?",
      options:["Cash Account","Sales Account","Capital Account","Purchase Account"],
      answer:"Cash Account" },
    { id:148, question:"In a credit purchase, Purchase Account is generally:",
      options:["Debited","Credited","Closed","Ignored"],
      answer:"Debited" },
    { id:150, question:"The rule \"Debit the receiver, Credit the giver\" applies to:",
      options:["Personal Account","Real Account","Nominal Account","Cash Account only"],
      answer:"Personal Account" },
    { id:151, question:"Which feature is used to maintain stock quantities?",
      options:["Inventory","Payroll","Cost Centre","Security"],
      answer:"Inventory" },
    { id:152, question:"A Stock Category is used to:",
      options:["Classify stock items","Create ledgers","Create companies","Record salaries"],
      answer:"Classify stock items" },
    { id:153, question:"Batch-wise details are useful for:",
      options:["Tracking batches of stock","Tracking employees","Tracking bank accounts","Tracking capital"],
      answer:"Tracking batches of stock" },
    { id:154, question:"Expiry Date is especially important for:",
      options:["Pharmaceutical products","Furniture","Machinery","Buildings"],
      answer:"Pharmaceutical products" },
    { id:155, question:"Which report shows stock quantity and value?",
      options:["Stock Summary","Balance Sheet","Trial Balance","Day Book"],
      answer:"Stock Summary" },
    { id:156, question:"Physical Stock Voucher is used to record:",
      options:["Actual physical stock","Salary","Bank payment","Sales return only"],
      answer:"Actual physical stock" },
    { id:157, question:"Delivery Note is related to:",
      options:["Delivery of goods","Receipt of cash","Salary payment","Bank transfer"],
      answer:"Delivery of goods" },
    { id:158, question:"Receipt Note is related to:",
      options:["Receipt of goods","Receipt of cash only","Sales","Salary"],
      answer:"Receipt of goods" },
    { id:159, question:"Rejection In is generally related to:",
      options:["Goods returned by customer","Goods returned to supplier","Salary","Cash receipt"],
      answer:"Goods returned by customer" },
    { id:160, question:"Rejection Out is generally related to:",
      options:["Goods returned to supplier","Goods returned by customer","Cash payment","Sales"],
      answer:"Goods returned to supplier" },
    { id:161, question:"GST is an example of:",
      options:["Indirect Tax","Direct Tax","Capital","Expense only"],
      answer:"Indirect Tax" },
    { id:162, question:"CGST is collected by the:",
      options:["Central Government","State Government","Local Government","Customer"],
      answer:"Central Government" },
    { id:163, question:"SGST is collected by the:",
      options:["State Government","Central Government","Bank","Supplier"],
      answer:"State Government" },
    { id:164, question:"IGST applies mainly to:",
      options:["Inter-state supplies","Intra-state supplies only","Salary","Capital"],
      answer:"Inter-state supplies" },
    { id:166, question:"A GST Tax Invoice is issued for:",
      options:["Taxable supply","Capital introduction only","Salary payment","Bank deposit"],
      answer:"Taxable supply" },
    { id:167, question:"Input Tax Credit helps a registered business to:",
      options:["Set off eligible input tax against output tax","Increase salary","Increase stock quantity","Create a company"],
      answer:"Set off eligible input tax against output tax" },
    { id:168, question:"GSTIN stands for:",
      options:["Goods and Services Tax Identification Number","General Sales Tax Identification Number","Goods Supply Tax Indian Number","Government Service Tax Identification Number"],
      answer:"Goods and Services Tax Identification Number" },
    { id:169, question:"GSTIN contains:",
      options:["15 characters","10 characters","12 characters","20 characters"],
      answer:"15 characters" },
    { id:170, question:"HSN is mainly used for:",
      options:["Goods classification","Employee classification","Bank classification","Company classification"],
      answer:"Goods classification" },
    { id:171, question:"SAC is mainly used for:",
      options:["Services classification","Goods classification only","Employee classification","Bank classification"],
      answer:"Services classification" },
    { id:172, question:"Tax Ledger should generally be created under:",
      options:["Duties & Taxes","Sundry Debtors","Capital Account","Fixed Assets"],
      answer:"Duties & Taxes" },
    { id:174, question:"Taxable amount before GST is called:",
      options:["Taxable Value","Tax Amount","Total Tax","Input Credit"],
      answer:"Taxable Value" },
    { id:175, question:"GST collected on sales is generally called:",
      options:["Output Tax","Input Tax","Capital Tax","Purchase Tax only"],
      answer:"Output Tax" },
    { id:176, question:"Which report displays all accounting transactions chronologically?",
      options:["Day Book","Balance Sheet","Stock Summary","Ratio Analysis"],
      answer:"Day Book" },
    { id:177, question:"Which report shows the financial position of a business?",
      options:["Balance Sheet","Day Book","Sales Register","Purchase Register"],
      answer:"Balance Sheet" },
    { id:178, question:"Which report shows the profitability of a business?",
      options:["Profit & Loss Account","Stock Summary","Day Book","Cash Book"],
      answer:"Profit & Loss Account" },
    { id:179, question:"Cash Book records:",
      options:["Cash transactions","Only credit sales","Only stock","Only salary"],
      answer:"Cash transactions" },
    { id:180, question:"Bank Book records:",
      options:["Bank transactions","Only cash transactions","Only stock","Only purchases"],
      answer:"Bank transactions" },
    { id:182, question:"Purchase Register contains:",
      options:["Purchase transactions","Sales transactions","Cash withdrawals only","Salary transactions"],
      answer:"Purchase transactions" },
    { id:183, question:"Payroll is used to manage:",
      options:["Employee salary and attendance-related information","Stock only","Customers only","Suppliers only"],
      answer:"Employee salary and attendance-related information" },
    { id:184, question:"Employee Groups are used to:",
      options:["Group employees","Group stock","Group ledgers","Group companies"],
      answer:"Group employees" },
    { id:185, question:"Pay Head is related to:",
      options:["Salary components","Stock items","Customers","Suppliers"],
      answer:"Salary components" },
    { id:186, question:"Basic Salary is an example of:",
      options:["Pay Head","Stock Group","Ledger Group","Voucher Type"],
      answer:"Pay Head" },
    { id:187, question:"Attendance Voucher is used to record:",
      options:["Employee attendance","Sales","Purchases","Bank transactions"],
      answer:"Employee attendance" },
    { id:188, question:"Cost Centre is useful for:",
      options:["Department-wise expense tracking","Stock counting","GST registration","Company creation"],
      answer:"Department-wise expense tracking" },
    { id:190, question:"Bank Reconciliation Statement is used to compare:",
      options:["Bank Book and Bank Statement","Sales and Purchase","Assets and Capital","Stock and Salary"],
      answer:"Bank Book and Bank Statement" },
    { id:191, question:"BRS stands for:",
      options:["Bank Reconciliation Statement","Bank Receipt Summary","Business Report System","Bank Record Sheet"],
      answer:"Bank Reconciliation Statement" },
    { id:192, question:"A cheque issued but not presented to the bank is a:",
      options:["Timing difference","Sales return","Purchase return","Capital entry"],
      answer:"Timing difference" },
    { id:193, question:"A cheque deposited but not cleared is generally shown as:",
      options:["Bank reconciliation difference","Sales","Purchase","Expense"],
      answer:"Bank reconciliation difference" },
    { id:194, question:"Ratio Analysis helps to evaluate:",
      options:["Financial performance","Employee attendance only","Stock quantity only","GST registration only"],
      answer:"Financial performance" },
    { id:195, question:"Working Capital is generally:",
      options:["Current Assets - Current Liabilities","Sales - Purchase","Capital - Drawings","Assets + Expenses"],
      answer:"Current Assets - Current Liabilities" },
    { id:196, question:"A higher current ratio generally indicates:",
      options:["Better short-term liquidity","Higher stock only","Higher sales only","Higher salary"],
      answer:"Better short-term liquidity" },
    { id:197, question:"Data Export can be used to:",
      options:["Transfer reports/data to other formats","Delete the company","Create a voucher automatically","Shut the computer"],
      answer:"Transfer reports/data to other formats" },
    { id:198, question:"Data Backup should ideally be taken:",
      options:["Regularly","Never","Only after deleting data","Only once"],
      answer:"Regularly" },
    { id:199, question:"The main advantage of Tally ERP 9 is:",
      options:["Integrated accounting and business management","Gaming","Video editing","Web browsing"],
      answer:"Integrated accounting and business management" },
    { id:200, question:"Which combination is important for a Tally accountant?",
      options:["Accounting, Inventory, GST and Reports","Drawing and Gaming","Video Editing and Music","Web Design only"],
      answer:"Accounting, Inventory, GST and Reports" }
  ],

  /* ==========================================================
     SET 3 — Tally ERP 9 MCQ2.pdf
     (Keyboard shortcuts + Journal Entry MCQs)  92 questions
     ========================================================== */
  tally3: [
    { id:1,  question:"Which key is used to select a company?",
      options:["Alt + F1","Alt + F2","Alt + F3","F11"],
      answer:"Alt + F1" },
    { id:2,  question:"Which key is used to shut a company?",
      options:["Alt + F1","Ctrl + F1","F2","Alt + F4"],
      answer:"Alt + F1" },
    { id:3,  question:"Which key opens Company Info?",
      options:["Alt + F3","Alt + F2","F11","Ctrl + F3"],
      answer:"Alt + F3" },
    { id:4,  question:"Which key is used to change the date?",
      options:["F1","F2","F3","F4"],
      answer:"F2" },
    { id:5,  question:"Which key is used to change the period?",
      options:["Alt + F2","Alt + F1","F2","F12"],
      answer:"Alt + F2" },
    { id:6,  question:"Which key opens Accounting Features?",
      options:["F10","F11","F12","F9"],
      answer:"F11" },
    { id:7,  question:"Which key opens Configuration?",
      options:["F11","F12","F2","F4"],
      answer:"F12" },
    { id:9,  question:"Shortcut key for Contra Voucher is:",
      options:["F4","F5","F6","F7"],
      answer:"F4" },
    { id:10, question:"Shortcut key for Payment Voucher is:",
      options:["F4","F5","F6","F7"],
      answer:"F5" },
    { id:11, question:"Shortcut key for Receipt Voucher is:",
      options:["F5","F6","F7","F8"],
      answer:"F6" },
    { id:12, question:"Shortcut key for Journal Voucher is:",
      options:["F6","F7","F8","F9"],
      answer:"F7" },
    { id:13, question:"Shortcut key for Sales Voucher is:",
      options:["F7","F8","F9","F10"],
      answer:"F8" },
    { id:14, question:"Shortcut key for Purchase Voucher is:",
      options:["F8","F9","F10","F7"],
      answer:"F9" },
    { id:15, question:"Which key is used to quit/exit Tally?",
      options:["Ctrl + Q","Alt + Q","Ctrl + E","Alt + E"],
      answer:"Ctrl + Q" },
    { id:17, question:"Which key is used to create a Ledger during voucher entry?",
      options:["Alt + C","Ctrl + C","Alt + L","F11"],
      answer:"Alt + C" },
    { id:18, question:"Which key is used to delete an entry/voucher?",
      options:["Alt + D","Ctrl + D","Alt + X","Ctrl + X"],
      answer:"Alt + D" },
    { id:19, question:"Which key is used to cancel a voucher?",
      options:["Alt + X","Alt + D","Ctrl + X","F12"],
      answer:"Alt + X" },
    { id:20, question:"Which key is used to insert a voucher in a report?",
      options:["Alt + I","Ctrl + I","Alt + V","F4"],
      answer:"Alt + I" },
    { id:21, question:"Which key is used to alter a voucher?",
      options:["Enter","Ctrl + A","Alt + A","F2"],
      answer:"Enter" },
    { id:22, question:"Which key is used to accept/save a screen?",
      options:["Ctrl + A","Ctrl + S","Alt + A","Enter only"],
      answer:"Ctrl + A" },
    { id:23, question:"Which key opens the Help menu?",
      options:["Alt + H","Ctrl + H","F1","F10"],
      answer:"F1" },
    { id:24, question:"Which key is used to open the Payment Voucher from Gateway of Tally?",
      options:["F4","F5","F6","F7"],
      answer:"F5" },
    { id:25, question:"Which key is used to open the Receipt Voucher?",
      options:["F5","F6","F7","F8"],
      answer:"F6" },
    { id:26, question:"Which key is used for Journal Voucher?",
      options:["F6","F7","F8","F9"],
      answer:"F7" },
    { id:27, question:"Which key is used for Sales Voucher?",
      options:["F7","F8","F9","F10"],
      answer:"F8" },
    { id:28, question:"Which key is used for Purchase Voucher?",
      options:["F8","F9","F10","F11"],
      answer:"F9" },
    { id:29, question:"Which key is used for Contra Voucher?",
      options:["F4","F5","F6","F7"],
      answer:"F4" },
    { id:30, question:"Which key is used to change the date while entering a voucher?",
      options:["F1","F2","F3","F4"],
      answer:"F2" },
    { id:31, question:"Which shortcut is used to open the Balance Sheet?",
      options:["B","Alt + B","Ctrl + B","F10"],
      answer:"Alt + B" },
    { id:32, question:"Which shortcut is used to open Profit & Loss Account?",
      options:["Alt + P","Alt + F1","Ctrl + P","F11"],
      answer:"Alt + P" },
    { id:34, question:"Which key is used to change the current report period?",
      options:["Alt + F2","Alt + F3","Alt + F1","F11"],
      answer:"Alt + F2" },
    { id:35, question:"Which shortcut is associated with exporting reports?",
      options:["Alt + E","Alt + P","Alt + D","Alt + C"],
      answer:"Alt + E" },
    { id:36, question:"Which shortcut is associated with e-mailing a report?",
      options:["Alt + M","Alt + E","Alt + P","Alt + S"],
      answer:"Alt + M" },
    { id:37, question:"Which key is used to switch between companies?",
      options:["F1","F2","F3","F4"],
      answer:"F1" },
    { id:38, question:"Which key opens the Company Features screen?",
      options:["F11","F12","F10","F9"],
      answer:"F11" },
    { id:39, question:"Which key opens Configuration?",
      options:["F11","F12","F10","F8"],
      answer:"F12" },
    { id:40, question:"Which key is used to go to the previous screen?",
      options:["Esc","Enter","F1","Ctrl + A"],
      answer:"Esc" },
    { id:42, question:"Which shortcut opens the Calculator?",
      options:["Ctrl + M","Ctrl + N","Ctrl + C","Ctrl + P"],
      answer:"Ctrl + M" },
    { id:43, question:"Which shortcut is used to create a new Ledger from a voucher screen?",
      options:["Alt + C","Alt + L","Ctrl + L","F12"],
      answer:"Alt + C" },
    { id:44, question:"Which shortcut is used to delete a selected voucher?",
      options:["Alt + D","Alt + X","Ctrl + D","Ctrl + X"],
      answer:"Alt + D" },
    { id:45, question:"Which shortcut is used to cancel a voucher?",
      options:["Alt + X","Alt + D","Ctrl + X","Ctrl + C"],
      answer:"Alt + X" },
    { id:46, question:"Which shortcut is used for printing?",
      options:["Alt + P","Alt + E","Alt + M","Alt + D"],
      answer:"Alt + P" },
    { id:47, question:"Which key is used to accept a voucher?",
      options:["Ctrl + A","Ctrl + S","Alt + A","F2"],
      answer:"Ctrl + A" },
    { id:48, question:"Which key is used to open the Help screen?",
      options:["F1","F2","F11","F12"],
      answer:"F1" },
    { id:49, question:"Which key is used to navigate to the next field?",
      options:["Enter","Esc","F2","Ctrl + A"],
      answer:"Enter" },
    { id:50, question:"Which key is commonly used to exit the current menu/screen?",
      options:["Esc","Enter","F1","F12"],
      answer:"Esc" },
    { id:51, question:"What is the Journal Entry for outstanding salary?",
      options:["Salary A/c Dr. To Outstanding Salary A/c","Cash A/c Dr. To Salary A/c","Salary A/c Dr. To Cash A/c","Outstanding Salary A/c Dr. To Salary A/c"],
      answer:"Salary A/c Dr. To Outstanding Salary A/c" },
    { id:52, question:"Rent paid in cash:",
      options:["Rent A/c Dr. To Cash A/c","Cash A/c Dr. To Rent A/c","Rent A/c Dr. To Bank A/c","Capital A/c Dr. To Rent A/c"],
      answer:"Rent A/c Dr. To Cash A/c" },
    { id:53, question:"Salary paid by bank:",
      options:["Salary A/c Dr. To Bank A/c","Bank A/c Dr. To Salary A/c","Salary A/c Dr. To Cash A/c","Capital A/c Dr. To Bank A/c"],
      answer:"Salary A/c Dr. To Bank A/c" },
    { id:54, question:"Depreciation charged on Machinery:",
      options:["Depreciation A/c Dr. To Machinery A/c","Machinery A/c Dr. To Depreciation A/c","Cash A/c Dr. To Machinery A/c","Machinery A/c Dr. To Cash A/c"],
      answer:"Depreciation A/c Dr. To Machinery A/c" },
    { id:55, question:"Interest received in cash:",
      options:["Cash A/c Dr. To Interest Received A/c","Interest Received A/c Dr. To Cash A/c","Bank A/c Dr. To Interest A/c","Interest A/c Dr. To Bank A/c"],
      answer:"Cash A/c Dr. To Interest Received A/c" },
    { id:56, question:"Commission received by bank:",
      options:["Bank A/c Dr. To Commission Received A/c","Commission A/c Dr. To Bank A/c","Cash A/c Dr. To Commission A/c","Commission A/c Dr. To Cash A/c"],
      answer:"Bank A/c Dr. To Commission Received A/c" },
    { id:58, question:"Owner withdrew cash for personal use:",
      options:["Drawings A/c Dr. To Cash A/c","Cash A/c Dr. To Drawings A/c","Capital A/c Dr. To Cash A/c","Cash A/c Dr. To Capital A/c"],
      answer:"Drawings A/c Dr. To Cash A/c" },
    { id:59, question:"Goods distributed as free samples:",
      options:["Advertisement A/c Dr. To Purchase A/c","Purchase A/c Dr. To Advertisement A/c","Sales A/c Dr. To Advertisement A/c","Cash A/c Dr. To Purchase A/c"],
      answer:"Advertisement A/c Dr. To Purchase A/c" },
    { id:60, question:"Goods donated to charity:",
      options:["Charity A/c Dr. To Purchase A/c","Purchase A/c Dr. To Charity A/c","Cash A/c Dr. To Charity A/c","Charity A/c Dr. To Cash A/c"],
      answer:"Charity A/c Dr. To Purchase A/c" },
    { id:61, question:"Bad debts written off:",
      options:["Bad Debts A/c Dr. To Debtor A/c","Debtor A/c Dr. To Bad Debts A/c","Cash A/c Dr. To Debtor A/c","Bad Debts A/c Dr. To Cash A/c"],
      answer:"Bad Debts A/c Dr. To Debtor A/c" },
    { id:62, question:"Provision for doubtful debts created:",
      options:["Profit & Loss A/c Dr. To Provision for Doubtful Debts A/c","Provision A/c Dr. To P&L A/c","Debtor A/c Dr. To Cash A/c","Cash A/c Dr. To Provision A/c"],
      answer:"Profit & Loss A/c Dr. To Provision for Doubtful Debts A/c" },
    { id:63, question:"Prepaid insurance adjustment:",
      options:["Prepaid Insurance A/c Dr. To Insurance A/c","Insurance A/c Dr. To Prepaid Insurance A/c","Cash A/c Dr. To Insurance A/c","Insurance A/c Dr. To Cash A/c"],
      answer:"Prepaid Insurance A/c Dr. To Insurance A/c" },
    { id:64, question:"Outstanding electricity expense:",
      options:["Electricity Expense A/c Dr. To Outstanding Electricity A/c","Outstanding Electricity A/c Dr. To Electricity Expense A/c","Cash A/c Dr. To Electricity A/c","Electricity A/c Dr. To Cash A/c"],
      answer:"Electricity Expense A/c Dr. To Outstanding Electricity A/c" },
    { id:65, question:"Accrued interest income:",
      options:["Accrued Interest A/c Dr. To Interest Income A/c","Interest Income A/c Dr. To Accrued Interest A/c","Cash A/c Dr. To Interest A/c","Interest A/c Dr. To Cash A/c"],
      answer:"Accrued Interest A/c Dr. To Interest Income A/c" },
    { id:66, question:"Salary outstanding is treated as:",
      options:["Liability","Asset","Income","Capital"],
      answer:"Liability" },
    { id:67, question:"Prepaid rent is treated as:",
      options:["Asset","Liability","Income","Capital"],
      answer:"Asset" },
    { id:68, question:"Depreciation is:",
      options:["Expense","Income","Liability","Capital"],
      answer:"Expense" },
    { id:69, question:"Bad Debts are:",
      options:["Expense/Loss","Income","Asset","Capital"],
      answer:"Expense/Loss" },
    { id:70, question:"Drawings reduce:",
      options:["Capital","Sales","Purchase","Creditors"],
      answer:"Capital" },
    { id:71, question:"Capital introduced in cash:",
      options:["Cash A/c Dr. To Capital A/c","Capital A/c Dr. To Cash A/c","Cash A/c Dr. To Sales A/c","Capital A/c Dr. To Sales A/c"],
      answer:"Cash A/c Dr. To Capital A/c" },
    { id:72, question:"Capital introduced through bank:",
      options:["Bank A/c Dr. To Capital A/c","Capital A/c Dr. To Bank A/c","Cash A/c Dr. To Capital A/c","Capital A/c Dr. To Cash A/c"],
      answer:"Bank A/c Dr. To Capital A/c" },
    { id:73, question:"Loan taken from bank:",
      options:["Bank A/c Dr. To Bank Loan A/c","Bank Loan A/c Dr. To Bank A/c","Cash A/c Dr. To Loan A/c","Loan A/c Dr. To Cash A/c"],
      answer:"Bank A/c Dr. To Bank Loan A/c" },
    { id:75, question:"Interest on loan paid:",
      options:["Interest on Loan A/c Dr. To Bank A/c","Bank A/c Dr. To Interest on Loan A/c","Loan A/c Dr. To Interest A/c","Interest A/c Dr. To Cash A/c"],
      answer:"Interest on Loan A/c Dr. To Bank A/c" },
    { id:76, question:"Purchase of furniture for cash:",
      options:["Furniture A/c Dr. To Cash A/c","Cash A/c Dr. To Furniture A/c","Purchase A/c Dr. To Cash A/c","Furniture A/c Dr. To Purchase A/c"],
      answer:"Furniture A/c Dr. To Cash A/c" },
    { id:77, question:"Purchase of machinery on credit:",
      options:["Machinery A/c Dr. To Supplier A/c","Supplier A/c Dr. To Machinery A/c","Purchase A/c Dr. To Supplier A/c","Cash A/c Dr. To Machinery A/c"],
      answer:"Machinery A/c Dr. To Supplier A/c" },
    { id:78, question:"Sale of an old asset for cash:",
      options:["Cash A/c Dr. To Asset A/c","Asset A/c Dr. To Cash A/c","Sales A/c Dr. To Cash A/c","Cash A/c Dr. To Sales A/c"],
      answer:"Cash A/c Dr. To Asset A/c" },
    { id:79, question:"Discount allowed to customer:",
      options:["Discount Allowed A/c Dr. To Customer A/c","Customer A/c Dr. To Discount Allowed A/c","Cash A/c Dr. To Discount A/c","Discount Received A/c Dr. To Customer A/c"],
      answer:"Discount Allowed A/c Dr. To Customer A/c" },
    { id:80, question:"Discount received from supplier:",
      options:["Supplier A/c Dr. To Discount Received A/c","Discount Received A/c Dr. To Supplier A/c","Cash A/c Dr. To Discount A/c","Supplier A/c Dr. To Cash A/c"],
      answer:"Supplier A/c Dr. To Discount Received A/c" },
    { id:81, question:"Cash withdrawn from bank for office use:",
      options:["Cash A/c Dr. To Bank A/c","Bank A/c Dr. To Cash A/c","Cash A/c Dr. To Capital A/c","Bank A/c Dr. To Capital A/c"],
      answer:"Cash A/c Dr. To Bank A/c" },
    { id:83, question:"Goods purchased from Ram on credit:",
      options:["Purchase A/c Dr. To Ram A/c","Ram A/c Dr. To Purchase A/c","Cash A/c Dr. To Ram A/c","Ram A/c Dr. To Cash A/c"],
      answer:"Purchase A/c Dr. To Ram A/c" },
    { id:84, question:"Goods sold to Shyam on credit:",
      options:["Shyam A/c Dr. To Sales A/c","Sales A/c Dr. To Shyam A/c","Cash A/c Dr. To Sales A/c","Shyam A/c Dr. To Cash A/c"],
      answer:"Shyam A/c Dr. To Sales A/c" },
    { id:85, question:"Payment made to creditor by cheque:",
      options:["Creditor A/c Dr. To Bank A/c","Bank A/c Dr. To Creditor A/c","Creditor A/c Dr. To Cash A/c","Purchase A/c Dr. To Bank A/c"],
      answer:"Creditor A/c Dr. To Bank A/c" },
    { id:86, question:"Amount received from debtor by cheque:",
      options:["Bank A/c Dr. To Debtor A/c","Debtor A/c Dr. To Bank A/c","Cash A/c Dr. To Debtor A/c","Debtor A/c Dr. To Cash A/c"],
      answer:"Bank A/c Dr. To Debtor A/c" },
    { id:87, question:"Rent outstanding is shown as:",
      options:["Current Liability","Fixed Asset","Income","Capital"],
      answer:"Current Liability" },
    { id:88, question:"Insurance paid in advance is shown as:",
      options:["Current Asset","Current Liability","Income","Capital"],
      answer:"Current Asset" },
    { id:89, question:"Which account is debited for an expense?",
      options:["Expense Account","Income Account","Liability Account","Capital Account"],
      answer:"Expense Account" },
    { id:90, question:"Which account is credited for income?",
      options:["Income Account","Expense Account","Asset Account","Drawings Account"],
      answer:"Income Account" },
    { id:91, question:"\"Debit all expenses and losses\" is a rule of:",
      options:["Nominal Account","Personal Account","Real Account","Liability Account"],
      answer:"Nominal Account" },
    { id:92, question:"\"Credit all incomes and gains\" is a rule of:",
      options:["Nominal Account","Personal Account","Real Account","Asset Account"],
      answer:"Nominal Account" },
    { id:93, question:"\"Debit the receiver, Credit the giver\" applies to:",
      options:["Personal Account","Real Account","Nominal Account","Expense Account"],
      answer:"Personal Account" },
    { id:94, question:"\"Debit what comes in, Credit what goes out\" applies to:",
      options:["Real Account","Personal Account","Nominal Account","Income Account"],
      answer:"Real Account" },
    { id:95, question:"Which account is debited when goods are purchased?",
      options:["Purchase Account","Sales Account","Cash Account","Capital Account"],
      answer:"Purchase Account" },
    { id:96, question:"Which account is credited when goods are sold?",
      options:["Sales Account","Purchase Account","Cash Account","Expense Account"],
      answer:"Sales Account" },
    { id:97, question:"Which account is debited when salary is paid?",
      options:["Salary Account","Cash Account","Capital Account","Sales Account"],
      answer:"Salary Account" },
    { id:98, question:"Which account is credited when cash is paid?",
      options:["Cash Account","Expense Account","Purchase Account","Salary Account"],
      answer:"Cash Account" },
    { id:100, question:"The main purpose of a Journal Entry is to:",
      options:["Record accounting transactions","Create a company","Print reports only","Change company name"],
      answer:"Record accounting transactions" }
  ]
};
